"""add_notification_queue_fallback

Revision ID: 20250124_000005
Revises: 20250124_000004
Create Date: 2025-01-24

R11-3: Add notification_queue_fallback table for PostgreSQL fallback when Redis is unavailable.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "20250124_000005"
down_revision: Union[str, None] = "20250124_000004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_queue_fallback",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("notification_type", sa.String(length=100), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notification_queue_fallback_created_at"),
        "notification_queue_fallback",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_queue_fallback_notification_type"),
        "notification_queue_fallback",
        ["notification_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_queue_fallback_priority"),
        "notification_queue_fallback",
        ["priority"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_queue_fallback_processed_at"),
        "notification_queue_fallback",
        ["processed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_queue_fallback_user_id"),
        "notification_queue_fallback",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "idx_notification_queue_processed_priority",
        "notification_queue_fallback",
        ["processed_at", "priority"],
        unique=False,
    )
    op.create_index(
        "idx_notification_queue_created",
        "notification_queue_fallback",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_notification_queue_created",
        table_name="notification_queue_fallback",
    )
    op.drop_index(
        "idx_notification_queue_processed_priority",
        table_name="notification_queue_fallback",
    )
    op.drop_index(
        op.f("ix_notification_queue_fallback_user_id"),
        table_name="notification_queue_fallback",
    )
    op.drop_index(
        op.f("ix_notification_queue_fallback_processed_at"),
        table_name="notification_queue_fallback",
    )
    op.drop_index(
        op.f("ix_notification_queue_fallback_priority"),
        table_name="notification_queue_fallback",
    )
    op.drop_index(
        op.f("ix_notification_queue_fallback_notification_type"),
        table_name="notification_queue_fallback",
    )
    op.drop_index(
        op.f("ix_notification_queue_fallback_created_at"),
        table_name="notification_queue_fallback",
    )
    op.drop_table("notification_queue_fallback")
    # ### end Alembic commands ###

