"""add_admin_action_escrow_table

Revision ID: 20250124_000003
Revises: 20250124_000002
Create Date: 2025-01-24

R18-4: Add admin_action_escrows table for dual control (four-eyes principle).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "20250124_000003"
down_revision: Union[str, None] = "20250124_000002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_action_escrows",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("operation_type", sa.String(length=50), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=True),
        sa.Column("operation_data", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("initiator_admin_id", sa.Integer(), nullable=False),
        sa.Column("approver_admin_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False, server_default="PENDING"),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["initiator_admin_id"],
            ["admins.id"],
        ),
        sa.ForeignKeyConstraint(
            ["approver_admin_id"],
            ["admins.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_admin_action_escrows_operation_type"),
        "admin_action_escrows",
        ["operation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_admin_action_escrows_target_id"),
        "admin_action_escrows",
        ["target_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_admin_action_escrows_initiator_admin_id"),
        "admin_action_escrows",
        ["initiator_admin_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_admin_action_escrows_approver_admin_id"),
        "admin_action_escrows",
        ["approver_admin_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_admin_action_escrows_status"),
        "admin_action_escrows",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_admin_action_escrows_expires_at"),
        "admin_action_escrows",
        ["expires_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_admin_action_escrows_expires_at"),
        table_name="admin_action_escrows",
    )
    op.drop_index(
        op.f("ix_admin_action_escrows_status"),
        table_name="admin_action_escrows",
    )
    op.drop_index(
        op.f("ix_admin_action_escrows_approver_admin_id"),
        table_name="admin_action_escrows",
    )
    op.drop_index(
        op.f("ix_admin_action_escrows_initiator_admin_id"),
        table_name="admin_action_escrows",
    )
    op.drop_index(
        op.f("ix_admin_action_escrows_target_id"),
        table_name="admin_action_escrows",
    )
    op.drop_index(
        op.f("ix_admin_action_escrows_operation_type"),
        table_name="admin_action_escrows",
    )
    op.drop_table("admin_action_escrows")
    # ### end Alembic commands ###

