"""add_admin_action_immutable

Revision ID: 20250124_000004
Revises: 20250124_000003
Create Date: 2025-01-24

R18-4: Add is_immutable flag to admin_actions table for audit log protection.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "20250124_000004"
down_revision: Union[str, None] = "20250124_000003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "admin_actions",
        sa.Column(
            "is_immutable",
            sa.Boolean(),
            nullable=False,
            server_default="false",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("admin_actions", "is_immutable")
    # ### end Alembic commands ###

