"""add_user_fsm_states_table

Revision ID: 20250124_000002
Revises: 20250124_000001
Create Date: 2025-01-24

R11-2: Add user_fsm_states table for PostgreSQL fallback when Redis is unavailable.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20250124_000002'
down_revision: Union[str, None] = '20250124_000001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_fsm_states',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('state', sa.String(length=255), nullable=True),
        sa.Column('data', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_fsm_states_user_id'), 'user_fsm_states', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_fsm_states_state'), 'user_fsm_states', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_fsm_states_state'), table_name='user_fsm_states')
    op.drop_index(op.f('ix_user_fsm_states_user_id'), table_name='user_fsm_states')
    op.drop_table('user_fsm_states')
    # ### end Alembic commands ###

